App_Dev/Controllers/BookController.cs
using App_Dev.Data;
using App_Dev.Models;
using App_Dev.Repository.IRepository;
using App_Dev.Utility;
using App_Dev.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Microsoft.Extensions.Hosting;
using System.Data;

namespace App_Dev.Controllers
{
    [Authorize(Roles = SD.Admin_Role +","+ SD.Store_Role)]
    public class BookController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public BookController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            IEnumerable<Book> bookList = _unitOfWork.Book.GetAll(includeProperties: "Category");
            return View(bookList);
        }
        //GET
        [HttpGet]
        public IActionResult Create()
        {
            BookVM bookVM = new BookVM()
            {
                Book = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                })
            };
            return View(bookVM);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BookVM obj, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\books");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Book.Image != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Book.Image.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    obj.Book.Image = @"images\books\" + fileName + extension;
                }
                _unitOfWork.Book.Add(obj.Book);
                _unitOfWork.Save();
                TempData["success"] = "Book created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            BookVM bookVM = new BookVM()
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                })
            };
            bookVM.Book = _unitOfWork.Book.GetFirstOrDefault(u => u.Id == id);
            return View(bookVM);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BookVM obj, IFormFile file)
        {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\books");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Book.Image != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Book.Image.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    obj.Book.Image = @"images\books\" + fileName + extension;
                }
                _unitOfWork.Book.Update(obj.Book);
                _unitOfWork.Save();
                TempData["success"] = "Book updated successfully";
                return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var obj = _unitOfWork.Book.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.Image.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Book.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Book deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

App_Dev/Controllers/CategoriesController.cs
using App_Dev.Data;
using App_Dev.Models;
using App_Dev.Repository.IRepository;
using App_Dev.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace App_Dev.Controllers
{
    [Authorize(Roles = SD.Admin_Role + "," + SD.Store_Role)]
    public class CategoriesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
            return View(objCategoryList);
        }

        ////GET
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Request request)
        {
                Category obj = new Category();
                obj.Name = request.Details;
               _unitOfWork.Category.Add(obj);
               _unitOfWork.Save();
               TempData["success"] = "Category created successfully"; 
               return RedirectToAction("Index");   
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if(categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if(obj == null)
            {
                return NotFound();
            }
            
            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

App_Dev/Controllers/OrderController.cs
using App_Dev.Data;
using App_Dev.Models;
using App_Dev.Repository.IRepository;
using App_Dev.Utility;
using App_Dev.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Security.Claims;

namespace App_Dev.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;
        public OrderController(ApplicationDbContext db)
        {
            _db = db;
        }
        [Authorize(Roles = SD.Admin_Role + "," + SD.Store_Role)]
        public IActionResult IndexAll()
        {
            IEnumerable<Order> orderList = _db.Orders;
            return View(orderList);
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            IEnumerable<Order> orderList = _db.Orders.Where(n => n.ApplicationUserId == claim.Value);
            return View(orderList);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Details(int orderId)
        {
            OrderVM orderVM = new()
            {
                Order = _db.Orders.Find(orderId),
                OrderItem = _db.OrderItems.Include("Book").Where(n => n.OrderId == orderId)
            };
            return View(orderVM);
        }
    }
}

App_Dev/Controllers/RequestController.cs
using App_Dev.Data;
using App_Dev.Models;
using App_Dev.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace App_Dev.Controllers
{
    [Authorize]
    public class RequestController : Controller
    {
        private readonly ApplicationDbContext _db;
        public RequestController(ApplicationDbContext db)
        {
            _db = db;
        }
        [Authorize(Roles = SD.Admin_Role)]
        public IActionResult IndexAll()
        {
            IEnumerable<Request> requestList = _db.Requests.Include("ApplicationUser");
            return View(requestList);
        }
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            IEnumerable<Request> requestList = _db.Requests.Include("ApplicationUser").Where(n => n.ApplicationUserId == claim.Value);
            return View(requestList);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Request request)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            request.ApplicationUserId = claim.Value;
            request.Status = "Waiting";
            _db.Requests.Add(request);
            _db.SaveChanges();
            TempData["success"] = "Send request successfully";
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int requestId)
        {
            Request request = _db.Requests.FirstOrDefault(n=>n.Id== requestId);
            return View(request);
        }
        [HttpPost]
        public IActionResult Edit(Request request)
        {
            _db.Requests.Update(request);
            if(request.Status == null)
            {
                request.Status = "Waiting";
            }
            _db.SaveChanges();
            TempData["success"] = "Request updated successfully";
            if (User.IsInRole(SD.Store_Role))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("IndexAll");
            }
        }
    }
}

App_Dev/Views/Shared/_Layout.cshtml
@using App_Dev.Utility;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App_Dev</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/App_Dev.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="background-color: black !important">
            <div class="container-fluid">
                <a style="color: white" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FPTBook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end align-items-center">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container page-wrapper">
        <div class="sidebar-container">
            <ul>
                <li class="sidebar-item">
                    <i class="bi bi-house-fill"></i>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="sidebar-item">
                    <i class="bi bi-cart2"></i>
                    <a asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                </li>
                <li class="sidebar-item">
                    <i class="bi bi-bag-dash"></i>
                    <a asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                </li>
                @if (User.IsInRole(SD.Store_Role) || User.IsInRole(SD.Admin_Role))
                {
                    <li class="sidebar-item">
                        <i class="bi bi-bag-check-fill"></i>
                        <a asp-area="" asp-controller="Order" asp-action="IndexAll">All Order</a>
                    </li>
                }
                @if (User.IsInRole(SD.Store_Role) || User.IsInRole(SD.Admin_Role))
                {
                    <li class="sidebar-item">
                        <i class="bi bi-journal-bookmark"></i>
                        <a asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                    </li>
                    <li class="sidebar-item">
                        <i class="bi bi-tag"></i>
                        <a asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                    </li>
                }
                @if (User.IsInRole(SD.Store_Role))
                {
                    <li class="sidebar-item">
                        <i class="bi bi-envelope-paper-heart"></i>
                        <a asp-area="" asp-controller="Request" asp-action="Index">Request</a>
                    </li>
                }
                @if (User.IsInRole(SD.Admin_Role))
                {
                    <li class="sidebar-item">
                        <i class="bi bi-envelope-paper"></i>
                        <a asp-area="" asp-controller="Request" asp-action="IndexAll">All Request</a>
                    </li>

                    <li class="sidebar-item">
                        <i class="bi bi-person-vcard"></i>
                        <a asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                    </li>
                    <li class="sidebar-item">
                        <i class="bi bi-person-plus"></i>
                        <a asp-area="Identity" asp-page="/Account/Register">Register account</a>
                    </li>
                }
            </ul>
            <div class="famous-author">
                <h6 class="famous-author-title">Famous Authors</h6>
                <ul>
                    <li class="famous-author-item"><i class="bi bi-pencil"></i>J. K. Rowling</li>
                    <li class="famous-author-item"><i class="bi bi-pencil"></i>Stephen King</li>
                    <li class="famous-author-item"><i class="bi bi-pencil"></i>Ernest Hemingway</li>
                    <li class="famous-author-item"><i class="bi bi-pencil"></i>Agatha Christie</li>
                </ul>
            </div>
        </div>
        <main style="position: relative" role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer style="background-color: black" class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FPTBook -
            @if (User.IsInRole(SD.Customer_Role))
            {
                <a asp-area="" asp-controller="Home" asp-action="Privacy"> Help</a>
            }
        </div>
    </footer>
    <script>
        const wrapper = document.querySelector(".page-wrapper");
        const wrapperHeight = wrapper.offsetHeight;
        console.log(wrapperHeight)
        if (wrapperHeight < 612) {
            console.log(wrapper.style.height);
            wrapper.style.height = "612px";
        }
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

App_Dev/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null) 
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["success"]')</script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">toastr.error('@TempData["error"]')</script>
}